/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppShipmentsRouteImport } from './routes/app.shipments'
import { Route as AppPalletsRouteImport } from './routes/app.pallets'
import { Route as AppInventoryRouteImport } from './routes/app.inventory'
import { Route as AppReportsIndexRouteImport } from './routes/app.reports.index'
import { Route as AppReportsPalletIdRouteImport } from './routes/app.reports.pallet.$id'
import { Route as AppReportsContainerIdRouteImport } from './routes/app.reports.container.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppShipmentsRoute = AppShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => AppRoute,
} as any)
const AppPalletsRoute = AppPalletsRouteImport.update({
  id: '/pallets',
  path: '/pallets',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsPalletIdRoute = AppReportsPalletIdRouteImport.update({
  id: '/reports/pallet/$id',
  path: '/reports/pallet/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsContainerIdRoute = AppReportsContainerIdRouteImport.update({
  id: '/reports/container/$id',
  path: '/reports/container/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/pallets': typeof AppPalletsRoute
  '/app/shipments': typeof AppShipmentsRoute
  '/app/reports/': typeof AppReportsIndexRoute
  '/app/reports/container/$id': typeof AppReportsContainerIdRoute
  '/app/reports/pallet/$id': typeof AppReportsPalletIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/pallets': typeof AppPalletsRoute
  '/app/shipments': typeof AppShipmentsRoute
  '/app/reports': typeof AppReportsIndexRoute
  '/app/reports/container/$id': typeof AppReportsContainerIdRoute
  '/app/reports/pallet/$id': typeof AppReportsPalletIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/pallets': typeof AppPalletsRoute
  '/app/shipments': typeof AppShipmentsRoute
  '/app/reports/': typeof AppReportsIndexRoute
  '/app/reports/container/$id': typeof AppReportsContainerIdRoute
  '/app/reports/pallet/$id': typeof AppReportsPalletIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/inventory'
    | '/app/pallets'
    | '/app/shipments'
    | '/app/reports/'
    | '/app/reports/container/$id'
    | '/app/reports/pallet/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/app/inventory'
    | '/app/pallets'
    | '/app/shipments'
    | '/app/reports'
    | '/app/reports/container/$id'
    | '/app/reports/pallet/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/inventory'
    | '/app/pallets'
    | '/app/shipments'
    | '/app/reports/'
    | '/app/reports/container/$id'
    | '/app/reports/pallet/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/shipments': {
      id: '/app/shipments'
      path: '/shipments'
      fullPath: '/app/shipments'
      preLoaderRoute: typeof AppShipmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pallets': {
      id: '/app/pallets'
      path: '/pallets'
      fullPath: '/app/pallets'
      preLoaderRoute: typeof AppPalletsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventory': {
      id: '/app/inventory'
      path: '/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports/': {
      id: '/app/reports/'
      path: '/reports'
      fullPath: '/app/reports/'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports/pallet/$id': {
      id: '/app/reports/pallet/$id'
      path: '/reports/pallet/$id'
      fullPath: '/app/reports/pallet/$id'
      preLoaderRoute: typeof AppReportsPalletIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports/container/$id': {
      id: '/app/reports/container/$id'
      path: '/reports/container/$id'
      fullPath: '/app/reports/container/$id'
      preLoaderRoute: typeof AppReportsContainerIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppInventoryRoute: typeof AppInventoryRoute
  AppPalletsRoute: typeof AppPalletsRoute
  AppShipmentsRoute: typeof AppShipmentsRoute
  AppReportsIndexRoute: typeof AppReportsIndexRoute
  AppReportsContainerIdRoute: typeof AppReportsContainerIdRoute
  AppReportsPalletIdRoute: typeof AppReportsPalletIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppInventoryRoute: AppInventoryRoute,
  AppPalletsRoute: AppPalletsRoute,
  AppShipmentsRoute: AppShipmentsRoute,
  AppReportsIndexRoute: AppReportsIndexRoute,
  AppReportsContainerIdRoute: AppReportsContainerIdRoute,
  AppReportsPalletIdRoute: AppReportsPalletIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
